[versions]
#noinspection AndroidGradlePluginVersion
agp = "8.6.0"
androidNestedProgress = "v1.0.2"
cameraCamera2 = "1.4.2"
cameraLifecycle = "1.4.2"
converterGson = "3.0.0"
coreSplashscreen = "1.0.1"
datastorePreferences = "1.1.7"
expandabletextview = "1.0.5"
flexbox = "3.0.0"
fragmentKtx = "1.8.8"
glide = "4.16.0"
igrefreshlayout = "1.0.3"
kotlin = "2.1.0"
coreKtx = "1.16.0"
junit = "4.13.2"
#noinspection GradleDependency
junitVersion = "1.2.1"
#noinspection GradleDependency
espressoCore = "3.6.1"
appcompat = "1.7.1"
#noinspection GradleDependency
lifecycleLivedataKtx = "2.9.1"
#noinspection GradleDependency
lifecycleRuntimeKtx = "2.9.1"
#noinspection GradleDependency
lifecycleViewmodelKtx = "2.9.1"
lingver = "1.3.0"
loggingInterceptor = "4.12.0"
lottie = "6.6.7"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
#noinspection GradleDependency
navigationUiKtx = "2.9.1"
photoview = "2.3.0"
popupDialog = "2.0.0"
retrofit = "3.0.0"
shimmer = "0.5.0"
swiperefreshlayout = "1.1.0"
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"
playServicesMaps = "19.2.0"
roomRuntimeAndroid = "2.7.2"
pagingRuntimeKtx = "3.1.0"
coreTesting = "2.1.0"
kotlinxCoroutinesTest = "1.6.1"
mockitoCore = "4.4.0"
mockitoInline = "4.4.0"
junitJupiter = "5.8.1"

[libraries]
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
android-nested-progress = { module = "com.github.emreesen27:Android-Nested-Progress", version.ref = "androidNestedProgress" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCamera2" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUiKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraLifecycle" }
expandabletextview = { module = "at.blogc:expandabletextview", version.ref = "expandabletextview" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
igrefreshlayout = { module = "com.github.Jamshid-M:IGRefreshLayout", version.ref = "igrefreshlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lingver = { module = "com.github.YarikSOffice:lingver", version.ref = "lingver" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
popup-dialog = { module = "com.saadahmedev.popup-dialog:popup-dialog", version.ref = "popupDialog" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
androidx-room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }

